name: default
permissions:
- nucleus.afk.base
- nucleus.firstspawn.base
- nucleus.getpos.base
- nucleus.helpop.base
- nucleus.home.base
- nucleus.home.list.base
- nucleus.home.set.base
- nucleus.ignore.base
- nucleus.ignorelist.base
- nucleus.info.base
- nucleus.kit.base
- nucleus.kit.list.base
- nucleus.kits.Claim
- nucleus.kits.vamp_guide
- nucleus.kits.Starter
- nucleus.list.base
- nucleus.mail.base
- nucleus.mail.send.base
- nucleus.message.base
- nucleus.motd.base
- nucleus.rtp.base
- nucleus.rules.base
- nucleus.spawn.base
- nucleus.time.base
- nucleus.teleport.tpa.base
- nucleus.teleport.tpaccept.base
- nucleus.teleport.tpahere.base
- nucleus.teleport.tpdeny.base
- nucleus.teleport.tptoggle.base
- nucleus.warp.base
- nucleus.warp.list.base
- griefprevention.user
- totaleconomy.command.balance
- totaleconomy.command.balancetop
- totaleconomy.command.pay
- vampirism.bind-action
- vampirism.changelog
- vampirism.eye
- vampirism.fang
- weight.0
